# Generated by Django 4.2.7 on 2025-07-27 15:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "Motorcycle"),
                            ("bicycle", "Bicycle"),
                            ("car", "Car"),
                            ("van", "Van"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vehicle_number", models.CharField(blank=True, max_length=20)),
                ("vehicle_model", models.CharField(blank=True, max_length=50)),
                ("is_available", models.BooleanField(default=True)),
                ("is_online", models.BooleanField(default=False)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "current_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "current_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("5.0")),
                        ],
                    ),
                ),
                ("total_deliveries", models.IntegerField(default=0)),
                ("successful_deliveries", models.IntegerField(default=0)),
                ("cancelled_deliveries", models.IntegerField(default=0)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Hourly rate in local currency",
                        max_digits=8,
                    ),
                ),
                (
                    "preferred_areas",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of preferred delivery areas",
                    ),
                ),
                (
                    "max_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Maximum delivery distance in kilometers",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "partner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_partner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "delivery_partners",
                "ordering": ["-rating", "-total_deliveries"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="delivery_pa_user_id_564746_idx"
                    ),
                    models.Index(
                        fields=["is_available"], name="delivery_pa_is_avai_dd6583_idx"
                    ),
                    models.Index(
                        fields=["is_online"], name="delivery_pa_is_onli_de0a1a_idx"
                    ),
                    models.Index(
                        fields=["current_lat", "current_lng"],
                        name="delivery_pa_current_88c5f6_idx",
                    ),
                    models.Index(
                        fields=["rating"], name="delivery_pa_rating_f8418c_idx"
                    ),
                    models.Index(
                        fields=["vehicle_type"], name="delivery_pa_vehicle_54aa60_idx"
                    ),
                ],
            },
        ),
    ]
